parameters:
  jobName:
  vmImage:
  spn:
  acr:
  image:
  tag:
  dockerFile:

jobs:
  - job: "${{ parameters.jobName }}"
    pool:
      vmImage: "${{ parameters.vmImage }}"
    
    steps:
      - template: "../steps/build-docker-image.yaml"
        parameters:
          spn: "${{ parameters.spn }}"
          acr: "${{ parameters.acr }}"
          image: "${{ parameters.image }}"
          tag: "${{ parameters.tag }}"
          dockerFile: "${{ parameters.dockerFile }}"

      - template: "../steps/push-docker-image.yaml"
        parameters:
          spn: "${{ parameters.spn }}"
          acr: "${{ parameters.acr }}"
          image: "${{ parameters.image }}"
          tag: "${{ parameters.tag }}"
