version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: "voting"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "changeme"
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080

  # api:
  #   image: voting-demo-api:latest
  #   restart: always
  #   environment:
  #     ConnectionStrings__VotingDb: "Host=db;Port=5432;Username=postgres;Password=changeme;Database=voting"
  #   ports:
  #     - 81:80