name: "$(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)"

# Trigger build when branches are updated
trigger:
  branches:
    include:
      - 'master'

# Agent jobs
jobs:
  - template: '../jobs/build-and-push-images.yaml'
    parameters:
      jobName: 'build_api_image_preprod'
      vmImage: 'ubuntu-16.04'
      spn: 'SPN-preprod-app-demo'
      acr: 'acrpreproddemo001.azurecr.io'
      image: 'voting-demo-api'
      tag: "$(Build.BuildId)"
      dockerFile: 'Dockerfile'

  - template: '../jobs/build-and-push-images.yaml'
    parameters:
      jobName: 'build_api_image_prod'
      vmImage: 'ubuntu-16.04'
      spn: 'SPN-prod-app-demo'
      acr: 'acrproddemo001.azurecr.io'
      image: 'voting-demo-api'
      tag: "$(Build.BuildId)"
      dockerFile: 'Dockerfile'
