name: "$(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)"

# Trigger build when branches are updated
trigger:
  branches:
    include:
      - 'develop'

# Agent jobs
jobs:
  - template: '../jobs/build-and-push-images.yaml'
    parameters:
      jobName: 'build_api_image'
      vmImage: 'ubuntu-16.04'
      spn: 'spn-dev-app-faurvoting'
      acr: 'acrdevfaurvoting001.azurecr.io'
      image: 'voting-demo-api'
      tag: "$(Build.BuildId)"
      dockerFile: 'Dockerfile'
