name: '$(Date:yyyyMMdd)$(Rev:.r)'

# Use the Azure DevOps pipeline templates
resources:
  repositories:
    - repository: 'pipelines'
      type: 'git'
      name: 'Azure/template-pipelines'

variables:
  - name: disable.coverage.autogenerate
    value: 'true'

trigger:
  branches:
    include:
      - 'develop'
      - 'master'

jobs:
  - template: jobs/sonar-process.yml@pipelines
    parameters:
      prepare_scanner_mode: 'MSBuild'
      prepare_sonarAdditionalProperties: |
        sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/**/*.trx
        sonar.coverage.exclusions=**/Migrations/*.cs,**/*Tests*/**/*
        sonar.cs.vscoveragexml.reportsPaths=$(Agent.TempDirectory)/**/*.coveragexml
      step_postPrepare:
        - template: 'steps/dotnet-restore-build-test.yml@pipelines'
