name: docker-build-push-ci
run-name: Build Docker image for branch ${{ github.ref_name }}

on:
  push: 
    branches: [develop, master]
  workflow_dispatch:

jobs:
  docker-build-push-image:
    uses: jblafage/workflow-templates/workflows/docker-build-push-image.yml@features/repo-layout
    with:
      image_repository: cloud/demo/voting-demo-api
      build_context: .
      dockerfile: Dockerfile
      registry_server: acrprdfaurecia001.azurecr.io
      registry_username: cloud-demo

    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
