on:
  pull_request:
  workflow_dispatch:

jobs:
  build-dotnet:
    uses: jblafage/workflow-templates/.github/workflows/dotnet-restore-build-test.yml@main
    with:
      dotnet_project: api_voting_demo.csproj
      dotnet_version: 6.0.x
      build_configuration: Release

  build-with-composite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: jblafage/workflow-templates/.github/actions/dotnet-restore-build-test@main
      with:
        dotnet_project: api_voting_demo.csproj
        run_tests: false
