on:
  pull_request:
  workflow_dispatch:

jobs:
  build-dotnet:
    uses: jblafage/workflow-templates/.github/workflows/dotnet-restore-build-test@main
    with:
      dotnet_project: api_voting_demo.csproj
